'use client';

import { Amplify } from 'aws-amplify';

// ✅ Later you'll replace this with a real amplify_outputs.json generated by Amplify.
// For now, keep it safe to run even without AWS by gating config.
export function configureAmplify() {
  // If you already have amplify_outputs.json, import it like:
  // import outputs from "../../amplify_outputs.json";
  // Amplify.configure(outputs);

  // Temporary placeholder (won’t authenticate until real values exist)
  const hasRealConfig =
    process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID &&
    process.env.NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID &&
    process.env.NEXT_PUBLIC_AWS_REGION;

  if (!hasRealConfig) return;

  Amplify.configure({
    Auth: {
      Cognito: {
        userPoolId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID!,
        userPoolClientId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID!,
        loginWith: { email: true },
      },
    },
    // API: { REST: ... } can be added later if you use Amplify API category
  });
}